###

POST http://localhost:3000/posts
Content-Type: application/json

{
    "owner": "Lee",
    "title": "My first post",
    "content": "This is my first post!"
}

###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts/6750a9e5a72100fd3a9796a0

###

GET http://localhost:3000/posts?owner=Lee